const actionTypes = {
  NEW_SONG_UPLOADED: "NEW_SONG_UPLOADED",
  JOINING_ROOM: "JOINING_ROOM",
  UPDATE_ROOM: "UPDATE_ROOM",
  ADD_ROOM: "ADD_ROOM",
  DELETE_ROOM: "DELETE_ROOM",
  UPDATE_BANNER: "UPDATE_BANNER",
  DELETE_BANNER: "DELETE_BANNER",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  SET_MOBILE_VIEW: "SET_MOBILE_VIEW",
  SET_THEME: "SET_THEME",
};

export default actionTypes;
